void main(){
///Date 28-jun-24
  List<Map<String,dynamic>> emp_data=[
    {
      "id":01,
      "name":"Vishal",
      "age":25,
      "city":"jaipur",
      "phone number":987654318,
      "email":"vishal32@gmail.com",
      "joining Date":21/02/2019,
      "salary":55000,
      "attendance":{
        "january":{
          1:"present",
          2:"absence",
          3:"present",
          4:"present",
          5:"present",
          6:"present",
          7:"holiday",
          8:"absence",
          9:"absence",
          10:"absence",
          11:"present",
          12:"present",
          13:"present",
          14:"holiday",
          15:"present",
          16:"absence",
          17:"present",
          18:"present",
          19:"absence",
          20:"present",
          21:"holiday",
          22:"present",
          23:"absence",
          24:"present",
          25:"absence",
          26:"present",
          27:"absence",
          28:"holiday",
          29:"present",
          30:"present",
          31:"present",

        },

      },

    },
    {
      "id":02,
      "name":"Viraj",
      "age":22,
      "city":"jodhpur",
      "phone number":9865321475,
      "email":"viraj3@gmail.com",
      "joining Date":21/05/2021,
      "salary":55000,
      "attendance":{
        "january":{
          1:"present",
          2:"absence",
          3:"present",
          4:"present",
          5:"present",
          6:"present",
          7:"holiday",
          8:"absence",
          9:"absence",
          10:"absence",
          11:"present",
          12:"present",
          13:"present",
          14:"holiday",
          15:"present",
          16:"absence",
          17:"present",
          18:"present",
          19:"absence",
          20:"present",
          21:"holiday",
          22:"present",
          23:"absence",
          24:"present",
          25:"absence",
          26:"present",
          27:"absence",
          28:"holiday",
          29:"present",
          30:"present",
          31:"present",

        },

      },

    },
    {
      "id":03,
      "name":"Arman",
      "age":28,
      "city":"jodhpur",
      "phone number":7896541235,
      "email":"arman12@gmail.com",
      "joining Date":03/05/2023,
      "salary":55000,
      "attendance":{
        "january":{
          1:"present",
          2:"absence",
          3:"present",
          4:"present",
          5:"present",
          6:"present",
          7:"holiday",
          8:"absence",
          9:"absence",
          10:"absence",
          11:"present",
          12:"present",
          13:"present",
          14:"holiday",
          15:"present",
          16:"absence",
          17:"present",
          18:"present",
          19:"absence",
          20:"present",
          21:"holiday",
          22:"present",
          23:"absence",
          24:"present",
          25:"absence",
          26:"present",
          27:"absence",
          28:"holiday",
          29:"present",
          30:"present",
          31:"present",

        },

      },

    },
    {
      "id":04,
      "name":"saurav",
      "age":22,
      "city":"jodhpur",
      "phone number":9512368745,
      "email":"saurav3@gmail.com",
      "joining Date":21/05/2019,
      "salary":55000,
      "attendance":{
        "january":{
          1:"present",
          2:"absence",
          3:"present",
          4:"present",
          5:"present",
          6:"present",
          7:"holiday",
          8:"absence",
          9:"absence",
          10:"absence",
          11:"present",
          12:"present",
          13:"present",
          14:"holiday",
          15:"present",
          16:"absence",
          17:"present",
          18:"present",
          19:"absence",
          20:"present",
          21:"holiday",
          22:"present",
          23:"absence",
          24:"present",
          25:"absence",
          26:"present",
          27:"absence",
          28:"holiday",
          29:"present",
          30:"present",
          31:"present",

        },

      },

    },
  ];
  print(emp_data);
}